name: Docker Image Build & Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{vars.DOCKER_USER}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build Docker Image
      run: |
        echo "CURR_DTTM=$(date +%Y%m%d_%H%M%S)" >> $GITHUB_ENV
        docker build . --file Dockerfile --tag $DOCKER_USER/ubuntu-py-aws-git:${{env.CURR_DTTM}}
        docker tag $DOCKER_USER/ubuntu-py-aws-git:${{env.CURR_DTTM}} $DOCKER_USER/ubuntu-py-aws-git:latest
        echo $GITHUB_ENV
    - name: Check Images
      run: docker images
    - name: Push Docker Image
      run: |
        docker push $DOCKER_USER/ubuntu-py-aws-git:${{env.CURR_DTTM}}
        docker push $DOCKER_USER/ubuntu-py-aws-git:latest