name: Docker Image Build & Push

on:
  push:
    branches: [ "main" ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{vars.DOCKER_USER}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    steps:
    - uses: actions/checkout@v3
    - name: Set CURR_DTTM
      id: set-curr-dttm
      run: |
        curr_dttm=$(date +%Y%m%d_%H%M%S)
        echo "curr_dttm=$curr_dttm" >> $GITHUB_OUTPUT
    - name: Check if Dockerfile is modified
      id: check-files
      run: |
        echo "========== check paths of modified files =========="
        git_version=$(git --version)
        echo "$git_version"
        git diff --name-only HEAD~1 HEAD > files.txt
        while IFS= read -r file
        do
          echo $file
          if [[ $file == 'Dockerfile' ]]; then
            echo "Dockerfile is modified"
            echo "run_job=true" >> $GITHUB_OUTPUT
            break
          fi
        done < files.txt
    - name: Docker Login
      if: steps.check-files.outputs.run_job == 'true'
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build Docker Image
      if: steps.check-files.outputs.run_job == 'true'
      run: |
        docker build . --file Dockerfile --tag $DOCKER_USER/ubuntu-py-aws-git:${{steps.set-curr-dttm.outputs.curr_dttm}}
        docker tag $DOCKER_USER/ubuntu-py-aws-git:${{steps.set-curr-dttm.outputs.curr_dttm}} $DOCKER_USER/ubuntu-py-aws-git:latest
    - name: Check Images
      run: docker images
    - name: Push Docker Image
      if: steps.check-files.outputs.run_job == 'true'
      run: |
        docker push $DOCKER_USER/ubuntu-py-aws-git:${{steps.set-curr-dttm.outputs.curr_dttm}}
        docker push $DOCKER_USER/ubuntu-py-aws-git:latest